imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%dbname_default%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
            base1:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%dbname_un%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
            base2:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%dbname_deux%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
            base3:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%dbname_trois%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default # précise l'em utilisé par défaut (lors de l'utilisation de la ligne de commande par exemple)
        entity_managers:
            default:
                connection: default
                mappings:
                    BSBetBundle : ~
                    BSMainBundle : ~
                    BSOfferBundle : ~
                    BSResultBundle : ~
                    BSTeamBundle : ~
            base1:
                connection: base1
                mappings:
                    BSBetBundle : ~
                    BSMainBundle : ~
                    BSOfferBundle : ~
                    BSResultBundle : ~
                    BSTeamBundle : ~
            base2:
                connection: base2
                mappings:
                    BSBetBundle : ~
                    BSMainBundle : ~
                    BSOfferBundle : ~
                    BSResultBundle : ~
                    BSTeamBundle : ~
            base3:
                connection: base3
                mappings:
                    BSBetBundle : ~
                    BSMainBundle : ~
                    BSOfferBundle : ~
                    BSResultBundle : ~
                    BSTeamBundle : ~


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
